pipeline {
    agent any

    environment {
        APP_NAME = 'taskflow'
        IMAGE_NAME = 'taskflow'
        IMAGE_TAG = "${env.BUILD_NUMBER}"
        HELM_RELEASE = 'taskflow'
        PYTHON = 'C:\\Users\\Naveen Gadde\\AppData\\Local\\Programs\\Python\\Python313\\python.exe'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('taskflow') {
                    bat "\"${PYTHON}\" -m pip install --upgrade pip"
                    bat "\"${PYTHON}\" -m pip install -r requirements.txt"
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('taskflow') {
                    bat "\"${PYTHON}\" -m pytest -q"
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('taskflow') {
                    bat "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
                }
            }
        }

        stage('Lint Helm Chart') {
            steps {
                bat 'helm lint taskflow\\helm\\taskflow'
                bat 'helm template taskflow taskflow\\helm\\taskflow > NUL'
            }
        }

        stage('Deploy to Kind') {
            steps {
                bat 'kubectl apply -f taskflow\\k8s\\namespace.yaml'
                bat "helm upgrade --install ${HELM_RELEASE} taskflow\\helm\\taskflow --namespace taskflow --create-namespace --set image.repository=${IMAGE_NAME} --set image.tag=${IMAGE_TAG} --set app.name=${APP_NAME}"
            }
        }

        stage('Verify Deployment') {
            steps {
                bat 'kubectl rollout status deployment/taskflow -n taskflow --timeout=180s'
                bat 'kubectl get pods -n taskflow'
                bat 'kubectl get svc -n taskflow'
            }
        }
    }
}
