apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
data:
  APP_NAME: {{ .Values.app.name | quote }}
  APP_ENV: {{ .Values.app.environment | quote }}
  APP_VERSION: {{ .Values.app.version | quote }}
  PORT: "5000"
